config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  resources :sessions, only: %i[ new create destroy ]

  resources :users, only: %i[ new create show edit update ]
    namespace :admin do
      resources :users
    end

  resources :tasks do
    collection do
      post :confirm
    end
  end

  resources :labels, only: %i[ new create index destroy ]

end

app/models/label.rb
class Label < ApplicationRecord
  
  validates :name, presence: true, length: { maximum:20 }
  validates :name, uniqueness: true

  has_many :label_tags, dependent: :destroy
  has_many :tasks, through: :label_tags
  belongs_to :user, optional: true

end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController

  def new
    @label = Label.new
  end

  def create
    @label = current_user.labels.build(label_params)

    if @label.save
      redirect_to labels_path, notice: "ラベル作成しました！"
    else
      render :new 
    end
  end

  def index
    @labels = Label.where(user_id: current_user.id)
    @labels_default = Label.where(user_id: nil) if current_user.admin == true
  end

  def destroy
    @label = Label.find(params[:id])
    @label.destroy
    redirect_to labels_path, notice: "ラベル削除しました"
  end

  private

  def label_params
    params.require(:label).permit(:name)
  end    

end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/index.html.erb
<h3>ラベル一覧</h3>
<div class="col-md-6">
  <table class="table table.hover">
    <tbody>
      <% @labels.each do |label| %>
      <tr>
        <th scope="col">name</th>
        <td scope="col"><%= label.name %></td>
        <td id="test-destroy"><%= link_to '削除', label_path(label.id), method: :delete,
            data: { confirm: '本当に削除して良いですか？' }, class:"btn btn-outline-danger" %></td>
      <% end %>
      </tr>
      <% if current_user_admin? %>
        <% @labels_default.each do |label| %>
        <tr>
          <th scope="col">name</th>
          <td scope="col"><%= label.name %></td>
          <td id="test-destroy"><%= link_to '削除', label_path(label.id), method: :delete,
              data: { confirm: '本当に削除して良いですか？' }, class:"btn btn-outline-danger" %></td>
        <% end %>
      <% end %>
      </tr>
    </tbody>
  </table>
</div>
<div class="user-show">
  <%= link_to 'ラベル作成', new_label_path, class:"btn btn-success" %>
  <%= link_to 'タスク一覧', tasks_path, class:"btn btn-dark" %>
</div>

app/views/labels/new.html.erb
<%= form_with(model:@label, local: true ) do |f| %>
  <% if @label.errors.any? %>
    <div class="error_explanation">
      <h3><%= @label.errors.count %><%= t('view.there_are_errors') %></h3>
      <ul>
        <% @label.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control col-md-6" %>
  </div>
  <div class="form-group">
    <%= f.submit nil, class:"btn btn-primary"  %>
  </div>
<% end %>