config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  resources :sessions, only: %i[ new create destroy ]

  resources :users, only: %i[ new create show edit update ]
    namespace :admin do
      resources :users
    end

  resources :tasks do
    collection do
      post :confirm
    end
  end

  resources :labels, only: %i[ new create index destroy ]

end

app/models/user.rb
class User < ApplicationRecord

  before_validation { email.downcase! }
  before_update :admin_update_limit
  before_destroy :admin_destroy_limit

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, 
                    length: { maximum: 30 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }

  has_many :tasks, dependent: :destroy
  delegate :title, 
           :content, 
           :expired,
           :status, 
           :priority, to: :user, prefix: true
  has_many :labels, dependent: :destroy
  
  private

  def admin_update_limit
    if User.where(admin: "true").count == 1 && self.will_save_change_to_admin?(from: true, to: false)
      throw :abort
    end
  end

  def admin_destroy_limit
    if User.where(admin: "true").count <= 1 && self.admin == true
      throw :abort
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_action :user_authority
  before_action :set_user, only: %i[ edit update destroy show ]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました"
    else
      render :new if @user.invalid?
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を編集しました"
    elsif @user.invalid?
      render :edit 
    else
      redirect_to admin_users_path, alert: "管理者ユーザーを0人することはできません"
    end
  end

  def index
    @users = User.select(:id, :name, :email, :admin).order(id: :asc).page(params[:page])
    @tasks_count = Task.all.count
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を削除しました"
    else
      redirect_to admin_users_path, alert: "管理者ユーザーを0人することはできません"
    end
  end

  def show
    @user_tasks = @user.tasks.order(created_at: :desc).page(params[:page])
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_comfirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_authority
    redirect_to tasks_path, alert: "管理者権限がありません" unless current_user_admin?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :login_required, only: %i[ new create ]
  before_action :current_user_cannot_create_user, only: %i[ new create ]
  before_action :set_current_user, only: %i[ show edit update ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "ユーザー「#{@user.name}」を登録し、ログインしました"
    else
      render :new if @user.invalid?
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー「#{@user.name}」を編集しました"
    else
      render :edit if @user.invalid?
    end
  end

  def show
  end


  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_comfirmation, :admin)
  end

  def set_current_user
    @user = User.find(params[:id])
    redirect_to tasks_path, alert: "権限がありません" if current_user.id != @user.id && current_user.admin == false
  end

  def current_user_cannot_create_user
    redirect_to tasks_path, alert: "2人目のユーザー作成はできません" if logged_in? && current_user.admin == false
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<% if user.errors.any? %>
  <div class="error_explanation">
    <h3><%= user.errors.count %><%= t('view.there_are_errors') %></h3>
    <ul>
      <% user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin, user], local: true ) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control col-md-6" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:"form-control col-md-6" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class:"form-control col-md-6" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:"form-control col-md-6" %>
  </div>
  <div class="form-group">
    <div class="form-check">
      <%= f.label :admin, class:"form-check-label" do %>
        <%= f.check_box :admin, class:"form-check-input" %>
        <span>管理者権限</span>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit nil, class:"btn btn-primary"  %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h3>ユーザー編集</h3>
<%= render partial: 'form', locals: { user: @user } %>

app/views/admin/users/index.html.erb
<h3>ユーザー一覧</h3>
<div class="col-md-10">
  <div class="admin-users-index">
    <%= link_to 'ユーザー作成', new_admin_user_path, class:"btn btn-primary" %>
  </div>
  <table class="table table-hover">
    <thead class="table-dark">
      <tr>
        <th scope="col" class="user-id">#</th>
        <th scope="col">名前</th>
        <th scope="col">アドレス</th>
        <th scope="col">管理者権限</th>
        <th scope="col">作成タスク数</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    <% n = 0 %>
    <% @users.each do |user| %>
    <% n += 1 %>
      <tr>
        <th class="user-id"><%= n %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <% if user.admin == true %>
            あり
          <% else %>
            なし
          <% end %>
        </td>
        <td><%= user.tasks.count %></td>
        <td id="test-info"><%= link_to '詳細', admin_user_path(user.id), class:"btn btn-outline-info" %></td>
        <td id="test-edit"><%= link_to '編集', edit_admin_user_path(user.id), class:"btn btn-outline-success" %></td>
        <td id="test-destroy"><%= link_to '削除', admin_user_path(user.id), method: :delete,
                data: { confirm: '本当に削除して良いですか？' }, class:"btn btn-outline-danger" %></td>
      <tr>
    <% end %>
    </tbody>
  </table>
  <div class="mb-3">
    <p>（総タスク数は<%= @tasks_count %>件です）</p>
    <%= paginate @users %>
    <%= page_entries_info @users %>
  </div>
</div>

app/views/admin/users/new.html.erb
<h3>ユーザー登録</h3>_
<div class="nav justify-content-end col-md-8">
  <%= link_to 'ユーザー一覧', admin_users_path, class:"nav-link" %>
</div>
<%= render partial: 'form', locals: { user: @user } %>

app/views/admin/users/show.html.erb
<div class="spece">
  <h3>ユーザー詳細（<%= @user.name %>）</h3>
</div>
<div class="col-md-12">
  <table class="table table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th scope="col">タイトル</th>
        <th scope="col">内容</th>
        <th scope="col">作成日時</th>
        <th scope="col">終了期限</th>
        <th scope="col">ステータス</th>
        <th scope="col">優先度</th>
      </tr>
    </thead>
    <tbody>
    <% @user_tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= l task.created_at, format: :short %></td>
        <td><%= l task.expired, format: :short %></td>
        <td><%= task.status %></td>
        <td><%= task[:priority] %></td>
      <tr>
    <% end %>
    </tbody>
  </table>
  <div class="mb-3">
    <%= paginate @user_tasks %>
    <%= page_entries_info @user_tasks %>
  </div>

</div>