config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  resources :sessions, only: %i[ new create destroy ]

  resources :users, only: %i[ new create show edit update ]
    namespace :admin do
      resources :users
    end

  resources :tasks do
    collection do
      post :confirm
    end
  end

  resources :labels, only: %i[ new create index destroy ]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top justify-content-end">
      <% if logged_in? %>
        <a class="navbar-brand"><span><%= current_user.name %></span>さん</a>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <% if logged_in? %>
            <li class="nav-item"><%= link_to 'タスク一覧', tasks_path, class:"nav-link" %></li>
            <li class="nav-item"><%= link_to 'マイページ', user_path(current_user.id), class:"nav-link" %></li>
            <li class="nav-item"><%= link_to 'ログアウト', session_path(current_user.id), method: :delete, class:"nav-link" %></li>
            <li class="nav-item"><%= link_to 'ラベル一覧', labels_path, class:"nav-link" %></li>
            <% if current_user_admin? %>
              <li class="nav-item"><%= link_to 'ユーザー一覧', admin_users_path, class:"nav-link" %></li>
            <% end %>
          <% else %>
            <li class="nav-item"><%= link_to 'ログイン', new_session_path, class:"nav-link" %></li>
            <li class="nav-item"><%= link_to 'ユーザー作成', new_user_path, class:"nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% if flash.notice.present? %>
        <div class="alert alert-success"><%= flash.notice %></div>
      <% elsif flash.alert.present? %>
        <div class="alert alert-danger"><%= flash.alert %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>